### ISSUE TITLE
Can not enable certificate

### ISSUE THREAD

**Issue by schwemmer** [jankais3r/SBB-XVA-1200#1]
Very cool, that you found a fix for the SSL error with the SBB app on iOS 13. I followed all the steps and received the certificate on my iPhone via AirDrop, however, when I do this:

> Go to Settings > General > About > Certificate Trust Settings and enable the newly installed certificate

all I can see is "Version" and a number, I can't see the created SBB certificate or enable it. Any ideas what I am doing wrong?

**Comment by jankais3r** [comment]
That sounds like if the certificate did not install properly. Once you Airdrop the certificate to your iPhone and you open the Settings app, the first entry (between iCloud account and Airplane mode) will be asking you to finish the installation. Once you do that, the certificate will be visible in the Trust Settings.
![IMG_1259](https://user-images.githubusercontent.com/2159464/59979161-45582f00-95e4-11e9-8592-793e571180e6.jpeg)

**Comment by schwemmer** [comment]
>  Once you Airdrop the certificate to your iPhone and you open the Settings app, the first entry (between iCloud account and Airplane mode) will be asking you to finish the installation. Once you do that, the certificate will be visible in the Trust Settings.

Yes, indeed. I missed that step. Now it is working and the SBB app is working again too now. Thank you so much! Awesome fix!

**Comment by schwemmer** [comment]
PS: I see that you've updated the README accordingly too. Thanks for that!
